"""SQLite data layer. The only module that touches the database.

No ORM: three tables do not justify one, and keeping the surface small means a
future storage swap only rewrites this file.
"""
import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone

from app import config

SCHEMA = """
CREATE TABLE IF NOT EXISTS sessions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    language    TEXT    NOT NULL,
    mode        TEXT    NOT NULL,
    scenario_id TEXT,
    topic       TEXT,
    started_at  TEXT    NOT NULL,
    ended_at    TEXT,
    report      TEXT,
    level       TEXT
);

CREATE TABLE IF NOT EXISTS messages (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id    INTEGER NOT NULL REFERENCES sessions(id),
    turn          INTEGER NOT NULL,
    speaker       TEXT    NOT NULL,
    text          TEXT    NOT NULL,
    correction    TEXT,
    suggestion    TEXT,
    audio_path    TEXT,
    pronunciation TEXT,
    created_at    TEXT    NOT NULL,
    UNIQUE(session_id, turn)
);

CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id, turn);
CREATE INDEX IF NOT EXISTS idx_sessions_language ON sessions(language, ended_at);

CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""

# Each entry migrates the database from version i to version i+1. Entries are
# append-only: editing one that has already run would leave databases with
# different shapes depending on when they were created.
MIGRATIONS = [
    # v0 -> v1: the Phase 1 schema
    [SCHEMA],
    # v1 -> v2: structured feedback fields (Phase 2A)
    [
        "ALTER TABLE messages ADD COLUMN ok INTEGER",
        "ALTER TABLE messages ADD COLUMN fixed TEXT",
        "ALTER TABLE messages ADD COLUMN tag TEXT",
    ],
    # v2 -> v3: scenarios the learner asked for, generated by the model
    # (Phase 2C). data/scenarios.json stays read-only: it is behind an
    # lru_cache, so mixing writes into it would mean owning cache
    # invalidation and file-write races for no gain.
    ["""
    CREATE TABLE IF NOT EXISTS user_scenarios (
        id             TEXT PRIMARY KEY,
        language       TEXT    NOT NULL,
        type           TEXT    NOT NULL,
        title          TEXT    NOT NULL,
        goal           TEXT,
        persona_prompt TEXT,
        max_turns      INTEGER,
        lines_json     TEXT,
        created_at     TEXT    NOT NULL,
        used_count     INTEGER NOT NULL DEFAULT 0
    );
    CREATE INDEX IF NOT EXISTS idx_user_scenarios_language
        ON user_scenarios(language, type);
    """],
]


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


@contextmanager
def connect():
    """Yield a connection with WAL enabled and rows accessible by column name.

    WAL keeps a reader from blocking the writer, which is what produces spurious
    "database is locked" errors under FastAPI's threadpool.
    """
    conn = sqlite3.connect(config.DB_PATH, timeout=10.0)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def schema_version() -> int:
    with connect() as conn:
        return conn.execute("PRAGMA user_version").fetchone()[0]


def _stamp_phase1_database(conn) -> None:
    """A database created before migrations existed sits at user_version 0 with
    the v1 schema already applied. Replaying MIGRATIONS[0] against it today would
    be harmless, since every statement in SCHEMA is CREATE ... IF NOT EXISTS — but
    that harmlessness is an accident of what SCHEMA happens to contain, and this
    repo's old habit was exactly "add a column to SCHEMA" (the bug this task
    exists to prevent). Stamping the database as v1 means the legacy path never
    executes MIGRATIONS[0] at all, so it stops depending on SCHEMA staying
    idempotent forever."""
    if conn.execute("PRAGMA user_version").fetchone()[0] != 0:
        return
    already = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='sessions'"
    ).fetchone()
    if already:
        conn.execute("PRAGMA user_version = 1")


def init_db() -> None:
    config.DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with connect() as conn:
        _stamp_phase1_database(conn)
        version = conn.execute("PRAGMA user_version").fetchone()[0]
        for step in MIGRATIONS[version:]:
            for statement in step:
                conn.executescript(statement)
            version += 1
            # PRAGMA does not accept bound parameters; version is an int we
            # computed ourselves, never user input.
            conn.execute(f"PRAGMA user_version = {version}")


def create_session(language, mode, scenario_id=None, topic=None) -> int:
    with connect() as conn:
        cur = conn.execute(
            "INSERT INTO sessions (language, mode, scenario_id, topic, started_at)"
            " VALUES (?, ?, ?, ?, ?)",
            (language, mode, scenario_id, topic, _now()),
        )
        return cur.lastrowid


def get_session(session_id):
    with connect() as conn:
        row = conn.execute("SELECT * FROM sessions WHERE id = ?", (session_id,)).fetchone()
    return dict(row) if row else None


def add_message(session_id, speaker, text, correction=None, suggestion=None,
                ok=None, fixed=None, tag=None) -> int:
    """Insert a message and auto-increment its turn within the session.

    Turn is computed inside the INSERT subquery to ensure atomicity: two concurrent
    calls for the same session will not both read MAX(turn) before either acquires
    the write lock, which would produce duplicate turn values. The UNIQUE constraint
    on (session_id, turn) catches any violation as a loud error.

    ok/fixed/tag are the structured half of the feedback; correction/suggestion
    stay as the prose explanation shown when the learner expands a chip.
    """
    with connect() as conn:
        cur = conn.execute(
            "INSERT INTO messages (session_id, turn, speaker, text, correction,"
            " suggestion, ok, fixed, tag, created_at)"
            " SELECT ?,"
            "        (SELECT COALESCE(MAX(turn), 0) + 1 FROM messages WHERE session_id = ?),"
            "        ?, ?, ?, ?, ?, ?, ?, ?",
            (session_id, session_id, speaker, text, correction, suggestion,
             ok, fixed, tag, _now()),
        )
        return cur.lastrowid


def get_messages(session_id) -> list[dict]:
    with connect() as conn:
        rows = conn.execute(
            "SELECT * FROM messages WHERE session_id = ? ORDER BY turn", (session_id,)
        ).fetchall()
    return [dict(r) for r in rows]


def delete_last_turn(session_id) -> tuple[int, list[str]]:
    """Drop the most recent learner turn and the bot reply that followed it.

    Undo exists because speech recognition mishears: a turn built on a sentence
    the learner did not say carries a bot reply and a correction that teach
    nothing, so they are removed rather than kept as history. Deleting the rows
    also frees their turn numbers, which matters because messages carries
    UNIQUE(session_id, turn) and add_message derives the next turn from MAX.

    Undo is used exactly when recognition mishears, which is often -- so the
    deleted turn's recording (if any) must not become an orphaned file nobody
    can ever find again. The rows carrying it are about to be deleted, which
    is the only chance to read audio_path back: after this, clear_session_audio
    can no longer see them, and stale_open_sessions' EXISTS clause means the
    sweep never will either. This module does no file operations, so the
    caller unlinks them.

    Returns (rows removed, audio paths of the deleted rows that had one). Rows
    removed is 2 for a normal turn, 1 if the bot reply never landed, 0 if the
    learner has not spoken yet.
    """
    with connect() as conn:
        last_user = conn.execute(
            "SELECT turn FROM messages WHERE session_id = ? AND speaker = 'user'"
            " ORDER BY turn DESC LIMIT 1",
            (session_id,),
        ).fetchone()
        if last_user is None:
            return 0, []
        paths = conn.execute(
            "SELECT audio_path FROM messages"
            " WHERE session_id = ? AND turn >= ? AND audio_path IS NOT NULL",
            (session_id, last_user["turn"]),
        ).fetchall()
        cur = conn.execute(
            "DELETE FROM messages WHERE session_id = ? AND turn >= ?",
            (session_id, last_user["turn"]),
        )
        return cur.rowcount, [r["audio_path"] for r in paths]


def set_message_audio(message_id, audio_path) -> None:
    with connect() as conn:
        conn.execute("UPDATE messages SET audio_path = ? WHERE id = ?", (audio_path, message_id))


def clear_session_audio(session_id) -> list[str]:
    """Forget the learner's recordings for one session.

    Nothing reads a recording after its session ends -- the report is written
    from the text transcript, and both places that play a clip back (the
    session screen and, later, shadowing) do so while the session is still
    running. Keeping them only accumulates the learner's voice on disk for no
    purpose.

    Returns the stored paths so the caller can unlink the files; this module
    does not touch the filesystem.
    """
    with connect() as conn:
        rows = conn.execute(
            "SELECT audio_path FROM messages"
            " WHERE session_id = ? AND audio_path IS NOT NULL",
            (session_id,),
        ).fetchall()
        conn.execute(
            "UPDATE messages SET audio_path = NULL WHERE session_id = ?", (session_id,)
        )
    return [r["audio_path"] for r in rows]


def stale_open_sessions(hours=24) -> list[int]:
    """Unfinished sessions with a recording still waiting to be collected.

    A closed browser tab leaves a session open forever -- there were eight in
    the real database when this was written. "Abandoned" is judged by the last
    activity in the session, not by when it started: a session opened
    yesterday and still being actively used must not look identical to one
    nobody has touched since. COALESCE falls back to started_at only for a
    session that never got a single message, since that is the only timestamp
    such a session has.

    Restricted to sessions that still hold a recording so a session already
    swept by a previous call drops out on its own, rather than being
    reprocessed on every future call forever. Its ended_at is deliberately
    left NULL -- that NULL is what keeps an abandoned session visible to
    this query at all. abandon_stale_sessions() stamps ended_at on this same
    population (same cutoff, same staleness test, minus the audio
    restriction), and the GET /sessions/resumable route always calls this
    function and unlinks what it returns *before* calling
    abandon_stale_sessions(). Stamp ended_at first, or swap that order, and
    these rows drop out of the `ended_at IS NULL` filter below with their
    recordings never collected -- stranding that audio on disk forever.
    """
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat(timespec="seconds")
    with connect() as conn:
        rows = conn.execute(
            "SELECT s.id FROM sessions s"
            " WHERE s.ended_at IS NULL"
            "   AND COALESCE("
            "         (SELECT MAX(m.created_at) FROM messages m WHERE m.session_id = s.id),"
            "         s.started_at"
            "       ) < ?"
            "   AND EXISTS (SELECT 1 FROM messages m2"
            "               WHERE m2.session_id = s.id AND m2.audio_path IS NOT NULL)"
            " ORDER BY s.id",
            (cutoff,),
        ).fetchall()
    return [r["id"] for r in rows]


def resumable_session(language):
    """The session the learner would want to come back to, if any.

    Only one is offered even when several are open: a list of half-finished
    conversations is a chore, not a feature. Sessions with no messages are
    skipped -- pressing 시작 and closing the tab leaves one of those, and there
    is nothing in it to resume. Script-mode sessions are excluded outright:
    the learner's position in the script (scriptIndex) lives only in the
    browser and is never persisted, so the app has no way to place them back
    where they left off -- and re-reading a short script from the top is
    natural anyway.
    """
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=24)).isoformat(timespec="seconds")
    with connect() as conn:
        row = conn.execute(
            "SELECT s.*, (SELECT COUNT(*) FROM messages m WHERE m.session_id = s.id) AS turns"
            " FROM sessions s"
            " WHERE s.language = ? AND s.ended_at IS NULL AND s.started_at >= ?"
            "   AND s.mode <> 'script'"
            "   AND EXISTS (SELECT 1 FROM messages m2 WHERE m2.session_id = s.id)"
            " ORDER BY s.id DESC LIMIT 1",
            (language, cutoff),
        ).fetchone()
    return dict(row) if row else None


def abandon_stale_sessions(hours=24) -> int:
    """Close sessions nobody came back to, so they stop being offered and stop
    being swept for recordings on every /end."""
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat(timespec="seconds")
    with connect() as conn:
        cur = conn.execute(
            "UPDATE sessions SET ended_at = ?"
            " WHERE ended_at IS NULL"
            "   AND COALESCE((SELECT MAX(m.created_at) FROM messages m"
            "                 WHERE m.session_id = sessions.id), started_at) < ?",
            (_now(), cutoff),
        )
        return cur.rowcount


def session_stats(session_id) -> dict:
    """Exact counts for the end-of-session report.

    Computed here rather than asked of the model: "which mistakes repeated" is
    a counting question, and a language model is the wrong tool for it. The
    model's job is to interpret the pattern, not to produce it.

    `없음` is a stored tag meaning the sentence was already correct, so it is
    excluded from the weakness counts rather than ranked as one. A turn whose
    `ok` is NULL never got feedback at all -- the model call failed -- and is
    counted as neither right nor wrong, but separately as `ungraded`: without
    that count a session where every grading call failed reads as flawless
    (wrong == 0) instead of as ungraded.
    """
    rows = [m for m in get_messages(session_id) if m["speaker"] == "user"]
    tags, sentences = {}, []
    for m in rows:
        if m["ok"] is None or m["ok"]:
            continue
        if m["tag"] and m["tag"] != "없음":
            tags[m["tag"]] = tags.get(m["tag"], 0) + 1
        if m["fixed"]:
            sentences.append({"said": m["text"], "fixed": m["fixed"], "tag": m["tag"]})
    return {"turns": len(rows),
            "wrong": sum(1 for m in rows if m["ok"] == 0),
            "ungraded": sum(1 for m in rows if m["ok"] is None),
            "tags": tags,
            "sentences": sentences}


def end_session(session_id, report, level) -> None:
    with connect() as conn:
        conn.execute(
            "UPDATE sessions SET ended_at = ?, report = ?, level = ? WHERE id = ?",
            (_now(), report, level, session_id),
        )


def latest_level(language) -> str:
    """Level of the most recently finished session in this language.

    Open sessions have a NULL level and are ignored.

    A single session's estimate is noise -- see stable_level, which judges
    the level over a window of recent sessions instead. Prefer that for
    anything that changes what the bot does (i+1 pitching, the level shown
    to the learner); this one stays for callers that already depend on it.
    """
    with connect() as conn:
        row = conn.execute(
            "SELECT level FROM sessions WHERE language = ? AND level IS NOT NULL"
            " ORDER BY ended_at DESC, id DESC LIMIT 1",
            (language,),
        ).fetchone()
    return row["level"] if row else "beginner"


def stable_level(language, recent=5, min_sessions=3):
    """The learner's level, judged over several sessions rather than one.

    A per-session estimate is noise: the same transcript run three times
    through the model produced beginner, intermediate and advanced, and the
    real database holds four consecutive one-turn sessions on one scenario
    recorded beginner, intermediate, intermediate, beginner. Anything that
    changes how the bot teaches -- i+1 pitching, and the level Phase D shows --
    has to read a stable value or it swings at random.

    The mode of the recent window, not the newest value and not an average:
    levels are an ordered set of three labels, and averaging labels is
    meaningless, so "usually" is the mode. On a tie, the most recent of the
    tied levels wins: a tie means the window does not clearly say one thing,
    so the newer evidence is the better guess.

    Returns None when the sample is too thin to say anything, which callers
    must handle rather than defaulting silently.
    """
    with connect() as conn:
        rows = conn.execute(
            "SELECT level FROM sessions"
            " WHERE language = ? AND ended_at IS NOT NULL AND level IS NOT NULL"
            " ORDER BY ended_at DESC LIMIT ?",
            (language, recent),
        ).fetchall()
    levels = [r["level"] for r in rows]
    if len(levels) < min_sessions:
        return None
    return max(levels, key=levels.count)


def list_sessions(limit=20) -> list[dict]:
    with connect() as conn:
        rows = conn.execute(
            "SELECT * FROM sessions ORDER BY id DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(r) for r in rows]


def get_setting(key, default=None):
    with connect() as conn:
        row = conn.execute("SELECT value FROM settings WHERE key = ?", (key,)).fetchone()
    return row["value"] if row else default


def set_setting(key, value) -> None:
    with connect() as conn:
        conn.execute(
            "INSERT INTO settings (key, value) VALUES (?, ?)"
            " ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            (key, value),
        )


def _scenario_row(row) -> dict:
    """Return a generated scenario in the same shape data/scenarios.json uses,
    so callers cannot tell a generated one from a built-in one."""
    item = {
        "id": row["id"], "language": row["language"], "type": row["type"],
        "title": row["title"], "goal": row["goal"],
        "used_count": row["used_count"],
    }
    if row["type"] == "free":
        item["persona_prompt"] = row["persona_prompt"]
        item["max_turns"] = row["max_turns"]
        item["lines"] = None
    else:
        item["lines"] = json.loads(row["lines_json"]) if row["lines_json"] else None
        item["persona_prompt"] = row["persona_prompt"]
        item["max_turns"] = row["max_turns"]
    return item


def add_user_scenario(item) -> None:
    with connect() as conn:
        conn.execute(
            "INSERT INTO user_scenarios (id, language, type, title, goal,"
            " persona_prompt, max_turns, lines_json, created_at)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (item["id"], item["language"], item["type"], item["title"],
             item.get("goal"), item.get("persona_prompt"), item.get("max_turns"),
             json.dumps(item["lines"], ensure_ascii=False) if item.get("lines") else None,
             _now()),
        )


def user_scenarios(language, kind=None) -> list[dict]:
    """Newest first: the thing the learner just asked for is the thing they
    are most likely to want again."""
    sql = "SELECT * FROM user_scenarios WHERE language = ?"
    args = [language]
    if kind is not None:
        sql += " AND type = ?"
        args.append(kind)
    sql += " ORDER BY created_at DESC, id DESC"
    with connect() as conn:
        return [_scenario_row(r) for r in conn.execute(sql, args)]


def get_user_scenario(scenario_id):
    with connect() as conn:
        row = conn.execute(
            "SELECT * FROM user_scenarios WHERE id = ?", (scenario_id,)
        ).fetchone()
    return _scenario_row(row) if row else None


def touch_user_scenario(scenario_id) -> None:
    with connect() as conn:
        conn.execute(
            "UPDATE user_scenarios SET used_count = used_count + 1 WHERE id = ?",
            (scenario_id,),
        )
