"""SQLite data layer. The only module that touches the database.

No ORM: three tables do not justify one, and keeping the surface small means a
future storage swap only rewrites this file.
"""
import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone

from app import config, scenarios

# scenarios.py imports this module back, so these two form an import cycle.
# It resolves because neither module *calls* into the other at module-body
# time -- only inside functions. Adding a scenarios.* call at the top level of
# this file (or a db.* call at the top level of that one) breaks the import
# outright, so don't.

SCHEMA = """
CREATE TABLE IF NOT EXISTS sessions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    language    TEXT    NOT NULL,
    mode        TEXT    NOT NULL,
    scenario_id TEXT,
    topic       TEXT,
    started_at  TEXT    NOT NULL,
    ended_at    TEXT,
    report      TEXT,
    level       TEXT
);

CREATE TABLE IF NOT EXISTS messages (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id    INTEGER NOT NULL REFERENCES sessions(id),
    turn          INTEGER NOT NULL,
    speaker       TEXT    NOT NULL,
    text          TEXT    NOT NULL,
    correction    TEXT,
    suggestion    TEXT,
    audio_path    TEXT,
    pronunciation TEXT,
    created_at    TEXT    NOT NULL,
    UNIQUE(session_id, turn)
);

CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id, turn);
CREATE INDEX IF NOT EXISTS idx_sessions_language ON sessions(language, ended_at);

CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""

# Each entry migrates the database from version i to version i+1. Entries are
# append-only: editing one that has already run would leave databases with
# different shapes depending on when they were created.
MIGRATIONS = [
    # v0 -> v1: the Phase 1 schema
    [SCHEMA],
    # v1 -> v2: structured feedback fields (Phase 2A)
    [
        "ALTER TABLE messages ADD COLUMN ok INTEGER",
        "ALTER TABLE messages ADD COLUMN fixed TEXT",
        "ALTER TABLE messages ADD COLUMN tag TEXT",
    ],
    # v2 -> v3: scenarios the learner asked for, generated by the model
    # (Phase 2C). data/scenarios.json stays read-only: it is behind an
    # lru_cache, so mixing writes into it would mean owning cache
    # invalidation and file-write races for no gain.
    #
    # used_count below is never written and never read. The counter it was
    # added for has no reader -- user_scenarios orders by created_at DESC,
    # which is what the learner actually wants -- so nothing maintains it and
    # every row stays 0. The column is left in place because this list is
    # append-only: dropping it would mean editing a step that has already run.
    # Reuse it if a later phase wants the count, but do not read any existing
    # row's value as meaning anything.
    ["""
    CREATE TABLE IF NOT EXISTS user_scenarios (
        id             TEXT PRIMARY KEY,
        language       TEXT    NOT NULL,
        type           TEXT    NOT NULL,
        title          TEXT    NOT NULL,
        goal           TEXT,
        persona_prompt TEXT,
        max_turns      INTEGER,
        lines_json     TEXT,
        created_at     TEXT    NOT NULL,
        used_count     INTEGER NOT NULL DEFAULT 0
    );
    CREATE INDEX IF NOT EXISTS idx_user_scenarios_language
        ON user_scenarios(language, type);
    """],
    # v3 -> v4: identity-based idempotency for script mode's bot-line storage.
    # script_index is set only by add_script_line_message -- every other row
    # (a free/lesson /chat turn, or a script session's own learner line via
    # /script-turn) leaves it NULL. SQLite treats each NULL as distinct under
    # a UNIQUE index, so those never collide with each other or with a script
    # line. For an actual script line, this constraint is what makes a second
    # row for the same index impossible at the database -- not a read-then-
    # write count, which can only ever be unlikely, not impossible, once
    # FastAPI's threadpool is in the picture (see add_message's own comment).
    [
        "ALTER TABLE messages ADD COLUMN script_index INTEGER",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_script_index"
        " ON messages(session_id, script_index)",
    ],
    # v4 -> v5: the theme library (docs/superpowers/specs/2026-09-14-monologue-
    # theme-library-design.md). Same columns as user_scenarios so scenarios.from_row
    # reads both, plus theme_id and situation. Rows come from scripts/build_library.py
    # and can be rebuilt from it; nothing here is the learner's own data.
    ["""
    CREATE TABLE IF NOT EXISTS library_scenarios (
        id             TEXT PRIMARY KEY,
        theme_id       TEXT    NOT NULL,
        situation      TEXT,
        language       TEXT    NOT NULL,
        type           TEXT    NOT NULL,
        title          TEXT    NOT NULL,
        goal           TEXT,
        persona_prompt TEXT,
        max_turns      INTEGER,
        lines_json     TEXT,
        created_at     TEXT    NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_library_theme
        ON library_scenarios(language, type, theme_id);
    """],
    # v5 -> v6: the review queue (docs/superpowers/specs/2026-09-14-monologue-
    # mypage-design.md, section "데이터"). The original design for this table
    # assumed only test data existed at the point it shipped, so it deliberately
    # did not backfill -- but by the time this migration actually runs there is
    # real correction history sitting in messages, and none of it should be lost
    # just because the table showed up after the fact. So this step also queues
    # one review per already-corrected turn, due today. Script sessions are
    # excluded: a script session's corrections are never meant to be practised
    # again the way a free/lesson turn's is (the spec's own words: "그 세션의
    # 교정은 이미 비웠다").
    ["""
    CREATE TABLE IF NOT EXISTS review_queue (
        id           INTEGER PRIMARY KEY AUTOINCREMENT,
        message_id   INTEGER NOT NULL UNIQUE,
        language     TEXT    NOT NULL,
        due_date     TEXT    NOT NULL,
        interval_d   INTEGER NOT NULL DEFAULT 1,
        passes       INTEGER NOT NULL DEFAULT 0,
        mastered_at  TEXT,
        created_at   TEXT    NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_review_due ON review_queue(language, mastered_at, due_date);
    INSERT OR IGNORE INTO review_queue (message_id, language, due_date, interval_d, passes, created_at)
    SELECT m.id, s.language, date('now', 'localtime'), 1, 0, strftime('%Y-%m-%dT%H:%M:%S+00:00', 'now')
      FROM messages m JOIN sessions s ON s.id = m.session_id
     WHERE m.speaker = 'user' AND m.ok = 0 AND m.fixed IS NOT NULL AND m.fixed <> '' AND s.mode <> 'script';
    """],
    # v6 -> v7: shadowing (docs/superpowers/specs/2026-09-19-monologue-shadowing-
    # design.md, "데이터"). A shadowing session is a script session with a flag;
    # each line attempt is one learner row keyed by script_index, with the verdict
    # and whether the text was peeked at. ok stays NULL: nothing here is graded,
    # so level, accuracy and weak spots never see these rows.
    [
        "ALTER TABLE sessions ADD COLUMN shadowing INTEGER NOT NULL DEFAULT 0",
        "ALTER TABLE messages ADD COLUMN matched INTEGER",
        "ALTER TABLE messages ADD COLUMN peeked INTEGER",
    ],
    # v7 -> v8: the weak-spot coach's daily note (docs/superpowers/specs/
    # 2026-09-19-monologue-mypage-tabs-coach-design.md, "서버"). One row per
    # language, overwritten each day it is made; nothing here is the learner's
    # own data -- it is rebuilt from messages whenever it is missing.
    ["""
    CREATE TABLE IF NOT EXISTS coach_notes (
        language   TEXT PRIMARY KEY,
        day        TEXT NOT NULL,
        body       TEXT NOT NULL,
        created_at TEXT NOT NULL
    );
    """],
    # v8 -> v9: 1분 말하기 회차 (docs/superpowers/specs/2026-09-19-monologue-
    # timed-speaking-design.md, "데이터"). Every round lives here; only round
    # 1's sentences also become messages rows, so level/accuracy/weak spots/
    # reviews count a minute once, not once per retelling.
    ["""
    CREATE TABLE IF NOT EXISTS timed_rounds (
        id             INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id     INTEGER NOT NULL REFERENCES sessions(id),
        round          INTEGER NOT NULL,
        seconds        REAL    NOT NULL,
        words          INTEGER NOT NULL,
        long_pauses    INTEGER NOT NULL,
        sentences_json TEXT    NOT NULL,
        native         TEXT,
        level          TEXT,
        audio_path     TEXT,
        created_at     TEXT    NOT NULL,
        UNIQUE(session_id, round)
    );
    """],
]


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _cutoff(hours=0, days=0) -> str:
    """A timestamp `hours`/`days` ago, in exactly the shape _now() writes.

    One definition on purpose: every caller compares it against a created_at or
    started_at column that _now() wrote, and a string comparison against a
    differently-formatted timestamp does not raise -- it silently matches
    nothing (or everything). The staleness sweep, the resume offer and the
    7-day counter all rest on this expression agreeing with _now(), so it is
    written down once next to it."""
    return (datetime.now(timezone.utc)
            - timedelta(hours=hours, days=days)).isoformat(timespec="seconds")


@contextmanager
def connect():
    """Yield a connection with WAL enabled and rows accessible by column name.

    WAL keeps a reader from blocking the writer, which is what produces spurious
    "database is locked" errors under FastAPI's threadpool.
    """
    conn = sqlite3.connect(config.DB_PATH, timeout=10.0)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def schema_version() -> int:
    with connect() as conn:
        return conn.execute("PRAGMA user_version").fetchone()[0]


def _stamp_phase1_database(conn) -> None:
    """A database created before migrations existed sits at user_version 0 with
    the v1 schema already applied. Replaying MIGRATIONS[0] against it today would
    be harmless, since every statement in SCHEMA is CREATE ... IF NOT EXISTS — but
    that harmlessness is an accident of what SCHEMA happens to contain, and this
    repo's old habit was exactly "add a column to SCHEMA" (the bug this task
    exists to prevent). Stamping the database as v1 means the legacy path never
    executes MIGRATIONS[0] at all, so it stops depending on SCHEMA staying
    idempotent forever."""
    if conn.execute("PRAGMA user_version").fetchone()[0] != 0:
        return
    already = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='sessions'"
    ).fetchone()
    if already:
        conn.execute("PRAGMA user_version = 1")


def init_db() -> None:
    config.DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with connect() as conn:
        _stamp_phase1_database(conn)
        version = conn.execute("PRAGMA user_version").fetchone()[0]
        for step in MIGRATIONS[version:]:
            for statement in step:
                conn.executescript(statement)
            version += 1
            # PRAGMA does not accept bound parameters; version is an int we
            # computed ourselves, never user input.
            conn.execute(f"PRAGMA user_version = {version}")


def create_session(language, mode, scenario_id=None, topic=None, shadowing=False) -> int:
    with connect() as conn:
        cur = conn.execute(
            "INSERT INTO sessions (language, mode, scenario_id, topic, shadowing, started_at)"
            " VALUES (?, ?, ?, ?, ?, ?)",
            (language, mode, scenario_id, topic, int(bool(shadowing)), _now()),
        )
        return cur.lastrowid


def get_session(session_id):
    with connect() as conn:
        row = conn.execute("SELECT * FROM sessions WHERE id = ?", (session_id,)).fetchone()
    return dict(row) if row else None


def add_message(session_id, speaker, text, correction=None, suggestion=None,
                ok=None, fixed=None, tag=None) -> int:
    """Insert a message and auto-increment its turn within the session.

    Turn is computed inside the INSERT subquery to ensure atomicity: two concurrent
    calls for the same session will not both read MAX(turn) before either acquires
    the write lock, which would produce duplicate turn values. The UNIQUE constraint
    on (session_id, turn) catches any violation as a loud error.

    ok/fixed/tag are the structured half of the feedback; correction/suggestion
    stay as the prose explanation shown when the learner expands a chip.
    """
    with connect() as conn:
        cur = conn.execute(
            "INSERT INTO messages (session_id, turn, speaker, text, correction,"
            " suggestion, ok, fixed, tag, created_at)"
            " SELECT ?,"
            "        (SELECT COALESCE(MAX(turn), 0) + 1 FROM messages WHERE session_id = ?),"
            "        ?, ?, ?, ?, ?, ?, ?, ?",
            (session_id, session_id, speaker, text, correction, suggestion,
             ok, fixed, tag, _now()),
        )
        return cur.lastrowid


def add_script_line_message(session_id, index, text) -> int | None:
    """Insert a script's bot line, keyed by its own index in the script.

    Identity-based, not a read-then-write count: script_index carries a
    UNIQUE(session_id, script_index) index (migration v3 -> v4), so the
    database itself rejects a second row for the same index -- regardless of
    arrival order or two requests racing each other. A prior version of this
    guard compared the index against len(get_messages(session_id)), which
    answers "how many messages exist", not "was this index stored" -- an
    interleaved or out-of-order sequence of indices could both duplicate a
    line and falsely reject a legitimate one. Mirrors add_message's own
    atomic turn allocation, and for the same reason its comment gives:
    FastAPI's threadpool plus WAL means a read-then-write check is not a
    guard, only a suggestion.

    Returns the new message id, or None if this index was already stored --
    an idempotent no-op, not an error.
    """
    with connect() as conn:
        try:
            cur = conn.execute(
                "INSERT INTO messages (session_id, turn, speaker, text, script_index, created_at)"
                " SELECT ?,"
                "        (SELECT COALESCE(MAX(turn), 0) + 1 FROM messages WHERE session_id = ?),"
                "        'bot', ?, ?, ?",
                (session_id, session_id, text, index, _now()),
            )
            return cur.lastrowid
        except sqlite3.IntegrityError:
            return None


def save_shadow_line(session_id, index, text, target, matched, peeked) -> int:
    """One shadowing attempt at script line `index`; a retry replaces the text
    and verdict in the same row, so the id -- and the recording attached to it
    -- stays put. UNIQUE(session_id, script_index) makes a second row for the
    index impossible even when two requests race. `peeked` only ever turns on:
    a line whose text was once shown was not shadowed blind, whatever a later
    attempt says."""
    with connect() as conn:
        conn.execute(
            "INSERT INTO messages (session_id, turn, speaker, text, fixed, script_index,"
            " matched, peeked, created_at)"
            " SELECT ?, (SELECT COALESCE(MAX(turn), 0) + 1 FROM messages WHERE session_id = ?),"
            "        'user', ?, ?, ?, ?, ?, ?"
            " ON CONFLICT(session_id, script_index) DO UPDATE SET"
            "   text = excluded.text, matched = excluded.matched,"
            "   peeked = MAX(peeked, excluded.peeked), created_at = excluded.created_at",
            (session_id, session_id, text, target, index, int(matched), int(peeked), _now()))
        return conn.execute(
            "SELECT id FROM messages WHERE session_id = ? AND script_index = ?",
            (session_id, index)).fetchone()[0]


def get_messages(session_id) -> list[dict]:
    with connect() as conn:
        rows = conn.execute(
            "SELECT * FROM messages WHERE session_id = ? ORDER BY turn", (session_id,)
        ).fetchall()
    return [dict(r) for r in rows]


def get_message(message_id):
    with connect() as conn:
        row = conn.execute("SELECT * FROM messages WHERE id = ?", (message_id,)).fetchone()
    return dict(row) if row else None


def delete_last_turn(session_id) -> tuple[int, list[str]]:
    """Drop the most recent learner turn and the bot reply that followed it.

    Undo exists because speech recognition mishears: a turn built on a sentence
    the learner did not say carries a bot reply and a correction that teach
    nothing, so they are removed rather than kept as history. Deleting the rows
    also frees their turn numbers, which matters because messages carries
    UNIQUE(session_id, turn) and add_message derives the next turn from MAX.

    Undo is used exactly when recognition mishears, which is often -- so the
    deleted turn's recording (if any) must not become an orphaned file nobody
    can ever find again. The rows carrying it are about to be deleted, which
    is the only chance to read audio_path back: after this, clear_session_audio
    can no longer see them, and stale_open_sessions' EXISTS clause means the
    sweep never will either. This module does no file operations, so the
    caller unlinks them.

    Returns (rows removed, audio paths of the deleted rows that had one). Rows
    removed is 2 for a normal turn, 1 if the bot reply never landed, 0 if the
    learner has not spoken yet.
    """
    with connect() as conn:
        last_user = conn.execute(
            "SELECT turn FROM messages WHERE session_id = ? AND speaker = 'user'"
            " ORDER BY turn DESC LIMIT 1",
            (session_id,),
        ).fetchone()
        if last_user is None:
            return 0, []
        paths = conn.execute(
            "SELECT audio_path FROM messages"
            " WHERE session_id = ? AND turn >= ? AND audio_path IS NOT NULL",
            (session_id, last_user["turn"]),
        ).fetchall()
        conn.execute(
            "DELETE FROM review_queue WHERE message_id IN"
            " (SELECT id FROM messages WHERE session_id = ? AND turn >= ?)",
            (session_id, last_user["turn"]),
        )
        cur = conn.execute(
            "DELETE FROM messages WHERE session_id = ? AND turn >= ?",
            (session_id, last_user["turn"]),
        )
        return cur.rowcount, [r["audio_path"] for r in paths]


def set_message_audio(message_id, audio_path) -> None:
    with connect() as conn:
        conn.execute("UPDATE messages SET audio_path = ? WHERE id = ?", (audio_path, message_id))


def clear_session_audio(session_id) -> list[str]:
    """Forget the learner's recordings for one session.

    Nothing reads a recording after its session ends -- the report is written
    from the text transcript, and both places that play a clip back (the
    session screen and, later, shadowing) do so while the session is still
    running. Keeping them only accumulates the learner's voice on disk for no
    purpose.

    Covers timed_rounds too -- a 1분 말하기 session's recordings live there,
    not in messages, and the same "nothing reads it again once the session is
    over" reasoning applies to them.

    Returns the stored paths so the caller can unlink the files; this module
    does not touch the filesystem.
    """
    with connect() as conn:
        rows = conn.execute(
            "SELECT audio_path FROM messages"
            " WHERE session_id = ? AND audio_path IS NOT NULL",
            (session_id,),
        ).fetchall()
        conn.execute(
            "UPDATE messages SET audio_path = NULL WHERE session_id = ?", (session_id,)
        )
        round_rows = conn.execute(
            "SELECT audio_path FROM timed_rounds"
            " WHERE session_id = ? AND audio_path IS NOT NULL",
            (session_id,),
        ).fetchall()
        conn.execute(
            "UPDATE timed_rounds SET audio_path = NULL WHERE session_id = ?", (session_id,)
        )
    return [r["audio_path"] for r in rows] + [r["audio_path"] for r in round_rows]


def _last_activity(alias):
    """SQL for a session's last activity: its newest message or timed round,
    or started_at when it has neither. A 1분 말하기 session writes rounds, not
    messages, until round 1 is graded -- judging it by messages alone would
    call a session in active use abandoned. Both subqueries are NULL when
    empty; the UNION ALL keeps MAX over whichever rows exist."""
    return ("COALESCE((SELECT MAX(t) FROM ("
            f"  SELECT m.created_at AS t FROM messages m WHERE m.session_id = {alias}.id"
            f"  UNION ALL SELECT tr.created_at FROM timed_rounds tr WHERE tr.session_id = {alias}.id"
            f")), {alias}.started_at)")


def stale_open_sessions(hours=24) -> list[int]:
    """Unfinished sessions with a recording still waiting to be collected.

    A closed browser tab leaves a session open forever -- there were eight in
    the real database when this was written. "Abandoned" is judged by the last
    activity in the session, not by when it started: a session opened
    yesterday and still being actively used must not look identical to one
    nobody has touched since. COALESCE falls back to started_at only for a
    session that never got a single message, since that is the only timestamp
    such a session has.

    A recording is a messages.audio_path or, for a 1분 말하기 session, a
    timed_rounds.audio_path; activity is the newest of either table's rows.

    Restricted to sessions that still hold a recording so a session already
    swept by a previous call drops out on its own, rather than being
    reprocessed on every future call forever. Its ended_at is deliberately
    left NULL -- that NULL is what keeps an abandoned session visible to
    this query at all. abandon_stale_sessions() stamps ended_at on this same
    population (same cutoff, same staleness test, minus the audio
    restriction), and the GET /sessions/resumable route always calls this
    function and unlinks what it returns *before* calling
    abandon_stale_sessions(). Stamp ended_at first, or swap that order, and
    these rows drop out of the `ended_at IS NULL` filter below with their
    recordings never collected -- stranding that audio on disk forever.
    """
    cutoff = _cutoff(hours=hours)
    with connect() as conn:
        rows = conn.execute(
            "SELECT s.id FROM sessions s"
            " WHERE s.ended_at IS NULL"
            f"   AND {_last_activity('s')} < ?"
            "   AND (EXISTS (SELECT 1 FROM messages m2"
            "                WHERE m2.session_id = s.id AND m2.audio_path IS NOT NULL)"
            "        OR EXISTS (SELECT 1 FROM timed_rounds tr"
            "                   WHERE tr.session_id = s.id AND tr.audio_path IS NOT NULL))"
            " ORDER BY s.id",
            (cutoff,),
        ).fetchall()
    return [r["id"] for r in rows]


def resumable_session(language):
    """The session the learner would want to come back to, if any.

    Only one is offered even when several are open: a list of half-finished
    conversations is a chore, not a feature. A session the learner never spoke
    in is skipped, and the speaker filter is the whole point of that clause:
    POST /sessions writes the bot's opening line before it returns, so *every*
    real free or lesson session has a message from the moment it is created,
    and a filter on messages alone would match all of them. Pressing 시작 and
    closing the tab is exactly the case being excluded -- there is nothing in
    such a session to come back to, only a greeting nobody answered.
    Script-mode sessions are excluded outright:
    the learner's position in the script (scriptIndex) lives only in the
    browser and is never persisted, so the app has no way to place them back
    where they left off -- and re-reading a short script from the top is
    natural anyway.
    Timed-mode sessions are excluded too: this card reopens a session as a
    conversation (POST /chat, a system prompt, a bot reply), and a timed
    session has none of that -- it is a running clock and a single question
    with no bot turn to answer. Opening one through this path would try to
    chat with it and break. An abandoned timed session still gets closed by
    the existing stale-session sweep, same as any other mode.
    """
    cutoff = _cutoff(hours=24)
    with connect() as conn:
        row = conn.execute(
            "SELECT s.*, (SELECT COUNT(*) FROM messages m WHERE m.session_id = s.id) AS turns"
            " FROM sessions s"
            " WHERE s.language = ? AND s.ended_at IS NULL AND s.started_at >= ?"
            "   AND s.mode NOT IN ('script', 'timed')"
            "   AND EXISTS (SELECT 1 FROM messages m2"
            "               WHERE m2.session_id = s.id AND m2.speaker = 'user')"
            " ORDER BY s.id DESC LIMIT 1",
            (language, cutoff),
        ).fetchone()
    return dict(row) if row else None


def abandon_stale_sessions(hours=24) -> int:
    """Close sessions nobody came back to, so they stop being offered and stop
    being swept for recordings on every /end."""
    cutoff = _cutoff(hours=hours)
    with connect() as conn:
        cur = conn.execute(
            "UPDATE sessions SET ended_at = ?"
            " WHERE ended_at IS NULL"
            f"   AND {_last_activity('sessions')} < ?",
            (_now(), cutoff),
        )
        return cur.rowcount


def active_minutes(session_id, pause_cap_seconds=300) -> int:
    """Time actually spent practising in this session, in minutes.

    Not `now - started_at`: a session can sit open and be resumed up to 24
    hours later (see resumable_session), so the raw elapsed time since it
    opened includes however long the learner was away, not just the time
    they spent talking. This instead sums the gaps between consecutive
    messages -- each capped at `pause_cap_seconds` -- so a pause longer than
    five minutes reads as the learner stepping away, not as five more
    minutes (or twenty-two hours) of practice. Fewer than two messages means
    there is no gap to measure, so 0.

    A report must never turn into an error over one line of timing: if any
    created_at can't be parsed, this returns 0 instead of raising. Each gap
    is also clamped to be non-negative before the cap is applied, so a
    clock oddity can't subtract from the total.
    """
    rows = get_messages(session_id)
    if len(rows) < 2:
        return 0
    total_seconds = 0.0
    try:
        for prev, cur in zip(rows, rows[1:]):
            gap = (datetime.fromisoformat(cur["created_at"])
                   - datetime.fromisoformat(prev["created_at"])).total_seconds()
            total_seconds += max(0, min(gap, pause_cap_seconds))
    except (ValueError, TypeError):
        return 0
    return int(total_seconds // 60)


def session_stats(session_id) -> dict:
    """Exact counts for the end-of-session report.

    Computed here rather than asked of the model: "which mistakes repeated" is
    a counting question, and a language model is the wrong tool for it. The
    model's job is to interpret the pattern, not to produce it.

    `없음` is a stored tag meaning the sentence was already correct, so it is
    excluded from the weakness counts rather than ranked as one. A turn whose
    `ok` is NULL never got feedback at all -- the model call failed -- and is
    counted as neither right nor wrong, but separately as `ungraded`: without
    that count a session where every grading call failed reads as flawless
    (wrong == 0) instead of as ungraded.
    """
    rows = [m for m in get_messages(session_id) if m["speaker"] == "user"]
    tags, sentences = {}, []
    for m in rows:
        if m["ok"] is None or m["ok"]:
            continue
        if m["tag"] and m["tag"] != "없음":
            tags[m["tag"]] = tags.get(m["tag"], 0) + 1
        if m["fixed"]:
            sentences.append({"said": m["text"], "fixed": m["fixed"], "tag": m["tag"]})
    return {"turns": len(rows),
            "wrong": sum(1 for m in rows if m["ok"] == 0),
            "ungraded": sum(1 for m in rows if m["ok"] is None),
            "tags": tags,
            "sentences": sentences}


def shadow_summary(session_id) -> dict:
    """The numbers a shadowing report shows, computed from the stored lines --
    never from the model. `hard` is every line said differently or said after
    peeking at the text: the ones worth another go."""
    with connect() as conn:
        rows = conn.execute(
            "SELECT id, script_index, text, fixed, matched, peeked FROM messages"
            " WHERE session_id = ? AND speaker = 'user' AND script_index IS NOT NULL"
            " ORDER BY script_index", (session_id,)).fetchall()
    return {
        "done": len(rows),
        "matched": sum(1 for r in rows if r["matched"]),
        "peeked": sum(1 for r in rows if r["peeked"]),
        "hard": [{"index": r["script_index"], "said": r["text"], "target": r["fixed"],
                  "message_id": r["id"]}
                 for r in rows if not r["matched"] or r["peeked"]],
    }


def end_session(session_id, report, level) -> None:
    with connect() as conn:
        conn.execute(
            "UPDATE sessions SET ended_at = ?, report = ?, level = ? WHERE id = ?",
            (_now(), report, level, session_id),
        )


def stable_level(language, recent=5, min_sessions=3):
    """The learner's level, judged over several sessions rather than one.

    This is the only level query. A `latest_level` -- the most recently
    finished session's own estimate -- lived here until Phase 2C and is gone:
    both of its callers moved to this function, and a single session's estimate
    is noise (see below), so nothing should read one again.

    A per-session estimate is noise: the same transcript run three times
    through the model produced beginner, intermediate and advanced, and the
    real database holds four consecutive one-turn sessions on one scenario
    recorded beginner, intermediate, intermediate, beginner. Anything that
    changes how the bot teaches -- i+1 pitching, and the level Phase D shows --
    has to read a stable value or it swings at random.

    The mode of the recent window, not the newest value and not an average:
    levels are an ordered set of three labels, and averaging labels is
    meaningless, so "usually" is the mode. On a tie, the most recent of the
    tied levels wins: a tie means the window does not clearly say one thing,
    so the newer evidence is the better guess.

    Returns None when the sample is too thin to say anything, which callers
    must handle rather than defaulting silently.
    """
    with connect() as conn:
        rows = conn.execute(
            "SELECT level FROM sessions"
            " WHERE language = ? AND ended_at IS NOT NULL AND level IS NOT NULL"
            " ORDER BY ended_at DESC LIMIT ?",
            (language, recent),
        ).fetchall()
    levels = [r["level"] for r in rows]
    if len(levels) < min_sessions:
        return None
    return max(levels, key=levels.count)


def home_stats(language) -> dict:
    """Numbers for the home screen. All computed, none estimated.

    `top_tags` withholds any tag until it has appeared at least three times: a
    weakness ranked off one mistake is a guess wearing the costume of a fact,
    and the home screen is where the learner decides what to practise. Up to
    three tags are returned, ranked by count. The `m.tag` in
    `ORDER BY n DESC, m.tag` is a secondary sort key that breaks ties on
    count in ascending tag order -- without it, ties would break on
    whatever order SQLite happens to visit rows in, and both the LIMIT 3
    cutoff and the panel's list would shuffle between runs.

    `streak` walks backwards from the most recent practice day, but that walk
    starts at *yesterday* when today has no messages yet, rather than always
    starting at today. Starting at today unconditionally would report 0 for a
    learner with a real ten-day streak who simply has not practised yet this
    morning -- and this number sits on the screen where they decide whether
    to open the app at all, so it must not die before the day is over. It
    only forgives one day: if the last practice was the day before yesterday
    or earlier, the streak is 0, full stop.

    Both the day list (SQL) and "today" (Python) are computed in local time,
    not UTC. created_at is stored as a UTC ISO string, and this app has
    exactly one learner, in Korea (UTC+9) -- comparing it against UTC dates
    would move the streak's day boundary to 9am KST instead of midnight,
    so a session at 08:00 and another at 20:00 the same Korean day would
    count as two different streak days, and the streak would silently reset
    every morning before the learner has had a chance to practise.

    That conversion assumes created_at always holds _now()'s ISO shape, and
    _now() is the only writer of it. If that ever stops being true,
    datetime(created_at, 'localtime') returns NULL for every row rather than
    raising, the day list fills with NULLs, and the streak reads 0 forever
    with no error anywhere to say why.
    """
    week_ago = _cutoff(days=7)
    with connect() as conn:
        week_turns = conn.execute(
            "SELECT COUNT(*) FROM messages m JOIN sessions s ON s.id = m.session_id"
            " WHERE s.language = ? AND m.speaker = 'user' AND m.created_at >= ?",
            (language, week_ago),
        ).fetchone()[0]
        fixed_total = conn.execute(
            "SELECT COUNT(*) FROM messages m JOIN sessions s ON s.id = m.session_id"
            " WHERE s.language = ? AND m.speaker = 'user' AND m.ok = 0",
            (language,),
        ).fetchone()[0]
        tag_rows = conn.execute(
            "SELECT m.tag, COUNT(*) n FROM messages m JOIN sessions s ON s.id = m.session_id"
            " WHERE s.language = ? AND m.speaker = 'user' AND m.ok = 0"
            "   AND m.tag IS NOT NULL AND m.tag <> '없음'"
            " GROUP BY m.tag HAVING n >= 3 ORDER BY n DESC, m.tag LIMIT 3",
            (language,),
        ).fetchall()
        days = [r[0] for r in conn.execute(
            "SELECT DISTINCT substr(datetime(m.created_at, 'localtime'), 1, 10) d"
            " FROM messages m JOIN sessions s ON s.id = m.session_id"
            " WHERE s.language = ? AND m.speaker = 'user'"
            " ORDER BY d DESC", (language,))]

    top_tags = [{"tag": r["tag"], "n": r["n"]} for r in tag_rows]

    streak = 0
    if days:
        today = datetime.now().date()
        if days[0] == today.isoformat():
            day = today
        elif days[0] == (today - timedelta(days=1)).isoformat():
            day = today - timedelta(days=1)
        else:
            day = None
        if day is not None:
            for stamp in days:
                if stamp != day.isoformat():
                    break
                streak += 1
                day -= timedelta(days=1)

    return {"streak": streak, "week_turns": week_turns,
            "fixed_total": fixed_total, "top_tags": top_tags}


def list_sessions(limit=20) -> list[dict]:
    with connect() as conn:
        rows = conn.execute(
            "SELECT * FROM sessions ORDER BY id DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(r) for r in rows]


def recent_sessions(language, limit=3) -> list[dict]:
    """홈 화면 오른쪽의 "최근 연습". 끝마친 세션만 -- 리포트가 있는 것 -- 최신순.

    ended_at IS NOT NULL 만으로는 부족하다. abandon_stale_sessions()도 아무도
    돌아오지 않은 세션에 ended_at을 찍지만, 그건 스윕이 자기 시점으로 찍는
    타임스탬프일 뿐 리포트는 쓰지 않는다 -- 그런 세션 중에는 봇의 첫 인사말만
    들어있는 것도 있다. 그래서 report IS NOT NULL도 함께 요구한다.

    list_sessions()는 언어로 거르지도, 세션별로 집계하지도 않는다. 그 함수에
    두 기능을 더하면 호출자마다 다른 절반만 쓰는 함수가 되므로 따로 쓴다.

    등급은 싣지 않는다. stable_level()이 이미 결론낸 대로 한 세션의 레벨 추정은
    노이즈이고 -- 같은 전사를 세 번 돌리면 세 번 다르게 나온다 -- 화면 한 칸을
    채우려고 그 결론을 되돌리지 않는다.

    title이 비는 경우가 실제로 있다(시나리오 없이 시작한 자유 세션). 빈 값을
    클라이언트로 내보내면 그 빈칸이 화면마다 다르게 메워지므로, 제목을 정하는
    건 scenarios 카탈로그를 아는 api.py의 몫이다. scenario_id는 여기서 풀지
    않고 그대로 실어 보낸다.
    """
    with connect() as conn:
        rows = conn.execute(
            "SELECT s.id, s.scenario_id, s.topic, s.ended_at, s.shadowing,"
            "       (SELECT COUNT(*) FROM messages m"
            "         WHERE m.session_id = s.id AND m.speaker = 'user' AND m.ok = 0)"
            "       AS fixed"
            " FROM sessions s"
            " WHERE s.language = ? AND s.ended_at IS NOT NULL AND s.report IS NOT NULL"
            " ORDER BY s.ended_at DESC, s.id DESC LIMIT ?",
            (language, limit),
        ).fetchall()
    return [dict(r) for r in rows]


def get_setting(key, default=None):
    with connect() as conn:
        row = conn.execute("SELECT value FROM settings WHERE key = ?", (key,)).fetchone()
    return row["value"] if row else default


def set_setting(key, value) -> None:
    with connect() as conn:
        conn.execute(
            "INSERT INTO settings (key, value) VALUES (?, ?)"
            " ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            (key, value),
        )


def add_user_scenario(item) -> None:
    with connect() as conn:
        conn.execute(
            "INSERT INTO user_scenarios (id, language, type, title, goal,"
            " persona_prompt, max_turns, lines_json, created_at)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (item["id"], item["language"], item["type"], item["title"],
             item.get("goal"), item.get("persona_prompt"), item.get("max_turns"),
             json.dumps(item["lines"], ensure_ascii=False) if item.get("lines") else None,
             _now()),
        )


def user_scenarios(language, kind=None) -> list[dict]:
    """Newest first: the thing the learner just asked for is the thing they
    are most likely to want again."""
    sql = "SELECT * FROM user_scenarios WHERE language = ?"
    args = [language]
    if kind is not None:
        sql += " AND type = ?"
        args.append(kind)
    sql += " ORDER BY created_at DESC, id DESC"
    with connect() as conn:
        return [scenarios.from_row(r) for r in conn.execute(sql, args)]


def get_user_scenario(scenario_id):
    with connect() as conn:
        row = conn.execute(
            "SELECT * FROM user_scenarios WHERE id = ?", (scenario_id,)
        ).fetchone()
    return scenarios.from_row(row) if row else None


def add_library_scenario(item) -> None:
    with connect() as conn:
        conn.execute(
            "INSERT INTO library_scenarios (id, theme_id, situation, language, type, title,"
            " goal, persona_prompt, max_turns, lines_json, created_at)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (item["id"], item["theme_id"], item.get("situation"), item["language"], item["type"],
             item["title"], item.get("goal"), item.get("persona_prompt"), item.get("max_turns"),
             json.dumps(item["lines"], ensure_ascii=False) if item.get("lines") else None,
             _now()),
        )


def _library_item(row) -> dict:
    item = scenarios.from_row(row)
    item["theme_id"] = row["theme_id"]
    item["situation"] = row["situation"]
    return item


def library_scenarios(language, theme_id, kind) -> list[dict]:
    with connect() as conn:
        rows = conn.execute(
            "SELECT * FROM library_scenarios WHERE language = ? AND theme_id = ? AND type = ?"
            " ORDER BY id", (language, theme_id, kind)).fetchall()
    return [_library_item(r) for r in rows]


def get_library_scenario(scenario_id):
    with connect() as conn:
        row = conn.execute("SELECT * FROM library_scenarios WHERE id = ?", (scenario_id,)).fetchone()
    return _library_item(row) if row else None


def last_started(scenario_ids) -> dict:
    """id -> the newest started_at among sessions opened on it. Ids never played
    are absent -- that absence is what library.pick_script reads as 'new'."""
    ids = list(scenario_ids)
    if not ids:
        return {}
    marks = ",".join("?" * len(ids))
    with connect() as conn:
        rows = conn.execute(
            f"SELECT scenario_id, MAX(started_at) AS last FROM sessions"
            f" WHERE scenario_id IN ({marks}) GROUP BY scenario_id", ids).fetchall()
    return {r["scenario_id"]: r["last"] for r in rows}


def practice_days(language, start, end) -> set:
    """Local dates (YYYY-MM-DD) in [start, end] on which the learner spoke.
    Local time for the same reason home_stats uses it (see its docstring).

    `m.created_at >= cutoff` runs before the localtime conversion so SQLite
    can rule most rows out with a plain string compare, rather than computing
    datetime(m.created_at, 'localtime') for every row in the table just to
    throw most of them away on the BETWEEN below. `cutoff` is local midnight
    of `start` *minus one day*, converted to UTC -- one exact day short of
    `start` would clip a message on `start`'s own local morning whenever the
    local zone runs ahead of UTC (as this app's Korea does): local
    00:05 on `start` is stored as roughly 15:05 UTC the day *before* `start`,
    which a same-day cutoff would exclude before the BETWEEN ever saw it.
    The BETWEEN clause is still what actually decides membership; this bound
    only narrows what reaches it, so results are unchanged."""
    local_tz = datetime.now().astimezone().tzinfo
    cutoff_local = datetime.combine(start - timedelta(days=1), datetime.min.time(), tzinfo=local_tz)
    cutoff = cutoff_local.astimezone(timezone.utc).isoformat(timespec="seconds")
    with connect() as conn:
        rows = conn.execute(
            "SELECT DISTINCT substr(datetime(m.created_at, 'localtime'), 1, 10) d"
            " FROM messages m JOIN sessions s ON s.id = m.session_id"
            " WHERE s.language = ? AND m.speaker = 'user' AND m.created_at >= ?"
            "   AND substr(datetime(m.created_at, 'localtime'), 1, 10) BETWEEN ? AND ?",
            (language, cutoff, start.isoformat(), end.isoformat())).fetchall()
    return {r[0] for r in rows}


def sessions_completed_since(language, start) -> int:
    """Sessions finished with a report on or after local midnight of `start`."""
    with connect() as conn:
        return conn.execute(
            "SELECT COUNT(*) FROM sessions WHERE language = ? AND report IS NOT NULL"
            " AND ended_at IS NOT NULL AND datetime(ended_at, 'localtime') >= ?",
            (language, f"{start.isoformat()} 00:00:00")).fetchone()[0]


def library_sessions(language, limit=50) -> list[dict]:
    with connect() as conn:
        rows = conn.execute(
            "SELECT scenario_id, mode, started_at, shadowing FROM sessions"
            " WHERE language = ? AND scenario_id LIKE 'lib-%'"
            " ORDER BY started_at DESC, id DESC LIMIT ?", (language, limit)).fetchall()
    return [dict(r) for r in rows]


def library_script_count(language) -> int:
    with connect() as conn:
        return conn.execute("SELECT COUNT(*) FROM library_scenarios WHERE language = ? AND type = 'script'",
                            (language,)).fetchone()[0]


def has_sessions(language) -> bool:
    with connect() as conn:
        return conn.execute("SELECT 1 FROM sessions WHERE language = ? LIMIT 1", (language,)).fetchone() is not None


def library_readiness(language) -> dict:
    """theme_id -> {'free': bool, 'script': count} for every theme with at least
    one row in this language, in one query. recommend() used to call
    library_scenarios (SELECT * + json.loads of every script's lines) and
    free_setup once per theme just to count rows -- up to ~40 queries
    hydrating full scenario bodies on every home load just to answer "is this
    theme ready, and with how many scripts". A theme absent here has no rows
    at all in this language."""
    with connect() as conn:
        rows = conn.execute(
            "SELECT theme_id, SUM(type = 'script') AS scripts, MAX(type = 'free') AS free"
            " FROM library_scenarios WHERE language = ? GROUP BY theme_id",
            (language,)).fetchall()
    return {r["theme_id"]: {"free": bool(r["free"]), "script": r["scripts"]} for r in rows}


# Spaced repetition (docs/superpowers/specs/2026-09-14-monologue-mypage-design.md,
# section "데이터"). Module-level so record_review reads them fresh on every call
# rather than closing over a value captured at import time -- tests monkeypatch
# REVIEW_PASSES_TO_MASTER to shorten the ladder, and that only works if the
# function looks the name up again each time it runs.
REVIEW_INTERVALS = (1, 3, 7, 14)
REVIEW_PASSES_TO_MASTER = 3


def enqueue_review(message_id, language, due) -> None:
    """Queue one corrected sentence for review, due on `due`. A silent no-op if
    this message is already queued (UNIQUE(message_id)) -- callers never need to
    check first, including the migration's own backfill."""
    with connect() as conn:
        conn.execute(
            "INSERT OR IGNORE INTO review_queue (message_id, language, due_date, created_at)"
            " VALUES (?, ?, ?, ?)", (message_id, language, due.isoformat(), _now()))


def get_review(review_id):
    with connect() as conn:
        row = conn.execute("SELECT * FROM review_queue WHERE id = ?", (review_id,)).fetchone()
    return dict(row) if row else None


def due_reviews(language, today, limit=20) -> list[dict]:
    """Up to `limit` not-yet-mastered reviews due on or before `today`, oldest
    due date first (ties broken by id, i.e. insertion order)."""
    with connect() as conn:
        rows = conn.execute(
            "SELECT r.id, r.message_id, m.text, m.fixed, m.correction, m.tag, r.created_at,"
            "       r.interval_d, r.passes, s.shadowing"
            " FROM review_queue r JOIN messages m ON m.id = r.message_id"
            "   JOIN sessions s ON s.id = m.session_id"
            " WHERE r.language = ? AND r.mastered_at IS NULL AND r.due_date <= ?"
            " ORDER BY r.due_date, r.id LIMIT ?", (language, today.isoformat(), limit)).fetchall()
    return [dict(r) for r in rows]


def review_counts(language, today) -> dict:
    """`due` counts exactly what due_reviews could list (same JOIN, no limit),
    so a row orphaned from its message is never promised. `total` is every row
    for the language, mastered or not: 0 means nothing was ever queued."""
    with connect() as conn:
        due = conn.execute(
            "SELECT COUNT(*) FROM review_queue r JOIN messages m ON m.id = r.message_id"
            " WHERE r.language = ? AND r.mastered_at IS NULL AND r.due_date <= ?",
            (language, today.isoformat())).fetchone()[0]
        mastered = conn.execute(
            "SELECT COUNT(*) FROM review_queue WHERE language = ? AND mastered_at IS NOT NULL",
            (language,)).fetchone()[0]
        total = conn.execute("SELECT COUNT(*) FROM review_queue WHERE language = ?",
                             (language,)).fetchone()[0]
    return {"due": due, "mastered": mastered, "total": total}


def record_review(review_id, result, today) -> dict:
    """Spaced repetition, one sentence at a time (spec table). pass climbs the
    interval ladder and masters on the third pass (which keeps its interval);
    fail starts over; skip only
    moves the card to tomorrow."""
    if result not in ("pass", "fail", "skip"):
        raise ValueError(result)
    with connect() as conn:
        row = conn.execute("SELECT * FROM review_queue WHERE id = ?", (review_id,)).fetchone()
        if row is None:
            raise KeyError(review_id)
        if row["mastered_at"] is not None:
            raise ValueError("already mastered")
        passes, interval, mastered_at = row["passes"], row["interval_d"], None
        if result == "pass":
            passes += 1
            if passes >= REVIEW_PASSES_TO_MASTER:
                # Spec table: the mastering pass leaves interval_d as it was.
                mastered_at = _now()
            else:
                steps = [i for i in REVIEW_INTERVALS if i > interval]
                interval = steps[0] if steps else REVIEW_INTERVALS[-1]
            due = today + timedelta(days=interval)
        elif result == "fail":
            passes, interval = 0, REVIEW_INTERVALS[0]
            due = today + timedelta(days=1)
        else:
            due = today + timedelta(days=1)
        conn.execute("UPDATE review_queue SET passes = ?, interval_d = ?, due_date = ?, mastered_at = ?"
                     " WHERE id = ?", (passes, interval, due.isoformat(), mastered_at, review_id))
    return {"id": review_id, "passes": passes, "interval_d": interval, "due_date": due.isoformat(),
            "mastered": mastered_at is not None}


def level_sample(language) -> dict:
    with connect() as conn:
        sessions = conn.execute("SELECT COUNT(*) FROM sessions WHERE language = ? AND report IS NOT NULL",
                                (language,)).fetchone()[0]
        utterances = conn.execute(
            "SELECT COUNT(*) FROM messages m JOIN sessions s ON s.id = m.session_id"
            " WHERE s.language = ? AND m.speaker = 'user'", (language,)).fetchone()[0]
    return {"sessions": sessions, "utterances": utterances}


def accuracy_since(language, since) -> dict:
    """Accuracy over graded, non-script learner turns from local `since` onward.

    Same bound as practice_days (see its docstring): `m.created_at >= cutoff`
    runs before the localtime conversion so SQLite can rule out most rows with
    a plain string compare instead of computing datetime(m.created_at,
    'localtime') for every message in the table just to throw most of them
    away on the date compare below. `cutoff` is local midnight of `since`
    *minus one day*, converted to UTC -- one exact day short of `since` would
    clip a message on `since`'s own local morning whenever the local zone runs
    ahead of UTC (as this app's Korea does). The date compare is still what
    actually decides membership; this bound only narrows what reaches it, so
    results are unchanged."""
    with connect() as conn:
        row = conn.execute(
            "SELECT COALESCE(SUM(m.ok = 1), 0) correct, COUNT(*) graded"
            " FROM messages m JOIN sessions s ON s.id = m.session_id"
            " WHERE s.language = ? AND s.mode <> 'script' AND m.speaker = 'user' AND m.ok IS NOT NULL"
            "   AND m.created_at >= ?"
            "   AND substr(datetime(m.created_at, 'localtime'), 1, 10) >= ?",
            (language, _local_cutoff(since), since.isoformat())).fetchone()
    return {"correct": row["correct"], "graded": row["graded"]}


_TAG_EXAMPLES = 3


def wrong_tag_counts(language) -> list[dict]:
    """Every wrong tag with its count and its newest few sentences: a count
    alone says *that* something goes wrong, the sentences say *what*. The
    same sentence said again (a review, a retry) is one example, not three
    copies of itself -- grouped before the LIMIT so the slots go to distinct
    sentences; `n` still counts every time."""
    with connect() as conn:
        rows = conn.execute(
            "SELECT m.tag, COUNT(*) n FROM messages m JOIN sessions s ON s.id = m.session_id"
            " WHERE s.language = ? AND m.speaker = 'user' AND m.ok = 0"
            "   AND m.tag IS NOT NULL AND m.tag <> '없음'"
            " GROUP BY m.tag ORDER BY n DESC, m.tag", (language,)).fetchall()
        out = []
        for r in rows:
            examples = conn.execute(
                "SELECT m.text, m.fixed, m.correction, MAX(m.created_at) last"
                " FROM messages m JOIN sessions s ON s.id = m.session_id"
                " WHERE s.language = ? AND m.speaker = 'user' AND m.ok = 0 AND m.tag = ?"
                " GROUP BY m.text, m.fixed ORDER BY last DESC, MAX(m.id) DESC LIMIT ?",
                (language, r["tag"], _TAG_EXAMPLES)).fetchall()
            out.append({"tag": r["tag"], "n": r["n"],
                        "examples": [{k: e[k] for k in ("text", "fixed", "correction")} for e in examples]})
    return out


def _local_cutoff(since) -> str:
    """UTC ISO string one day before local midnight of `since` -- a cheap
    string prefilter; the localtime date compare still decides membership
    (same reasoning as accuracy_since's docstring)."""
    local_tz = datetime.now().astimezone().tzinfo
    cutoff_local = datetime.combine(since - timedelta(days=1), datetime.min.time(), tzinfo=local_tz)
    return cutoff_local.astimezone(timezone.utc).isoformat(timespec="seconds")


_COACH_WHERE = (
    " FROM messages m JOIN sessions s ON s.id = m.session_id"
    " WHERE s.language = ? AND s.mode <> 'script' AND m.speaker = 'user' AND m.ok = 0"
    "   AND m.fixed IS NOT NULL AND m.fixed <> ''"
    "   AND m.created_at >= ? AND substr(datetime(m.created_at, 'localtime'), 1, 10) >= ?"
)


def coach_inputs(language, since, limit=30) -> list[dict]:
    """The newest `limit` distinct wrong sentences, each with `reps`, how many
    times it was said: grouped before the LIMIT so a sentence said five times
    takes one slot, and the model still hears that it keeps coming back."""
    with connect() as conn:
        rows = conn.execute(
            "SELECT m.text, m.fixed, m.tag, m.correction, COUNT(*) reps, MAX(m.created_at) last" + _COACH_WHERE +
            " GROUP BY m.text, m.fixed ORDER BY last DESC, MAX(m.id) DESC LIMIT ?",
            (language, _local_cutoff(since), since.isoformat(), limit)).fetchall()
    return [{k: r[k] for k in ("text", "fixed", "tag", "correction", "reps")} for r in rows]


def wrong_count_since(language, since) -> int:
    with connect() as conn:
        return conn.execute("SELECT COUNT(*)" + _COACH_WHERE,
                            (language, _local_cutoff(since), since.isoformat())).fetchone()[0]


def get_coach(language) -> dict | None:
    with connect() as conn:
        row = conn.execute("SELECT day, body FROM coach_notes WHERE language = ?", (language,)).fetchone()
    return {"day": row["day"], "items": json.loads(row["body"])} if row else None


def save_coach(language, day, items) -> None:
    with connect() as conn:
        conn.execute(
            "INSERT INTO coach_notes (language, day, body, created_at) VALUES (?, ?, ?, ?)"
            " ON CONFLICT(language) DO UPDATE SET day = excluded.day, body = excluded.body,"
            " created_at = excluded.created_at",
            (language, day, json.dumps(items, ensure_ascii=False), _now()))


# 1분 말하기 (docs/superpowers/specs/2026-09-19-monologue-timed-speaking-design.md,
# "데이터"). Every round of a session lives in timed_rounds, keyed by
# (session_id, round); only round 1's sentences also become messages rows
# (a later task's job), so a minute counts once toward level/accuracy/weak
# spots/reviews, not once per retelling.
def next_round(session_id) -> int:
    with connect() as conn:
        row = conn.execute(
            "SELECT MAX(round) FROM timed_rounds WHERE session_id = ?", (session_id,)
        ).fetchone()
    return (row[0] or 0) + 1


def _fresh_sentences_json(sentences) -> str:
    return json.dumps(
        [{"text": s, "graded": False, "ok": None, "fixed": None, "correction": None,
          "suggestion": None, "tag": None, "message_id": None} for s in sentences],
        ensure_ascii=False,
    )


def add_round(session_id, round, seconds, words, long_pauses, sentences, audio_path) -> int:
    """sentences is a list of sentence strings, fresh off timed.round_stats --
    nothing has graded them yet, so every row starts graded: False and every
    other field None."""
    sentences_json = _fresh_sentences_json(sentences)
    with connect() as conn:
        conn.execute(
            "INSERT INTO timed_rounds (session_id, round, seconds, words, long_pauses,"
            " sentences_json, audio_path, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (session_id, round, seconds, words, long_pauses, sentences_json, audio_path, _now()),
        )
    return round


def get_rounds(session_id) -> list[dict]:
    with connect() as conn:
        rows = conn.execute(
            "SELECT * FROM timed_rounds WHERE session_id = ? ORDER BY round", (session_id,)
        ).fetchall()
    out = []
    for r in rows:
        item = dict(r)
        item["sentences"] = json.loads(item.pop("sentences_json"))
        out.append(item)
    return out


def set_round_sentences(session_id, round, sentences) -> None:
    with connect() as conn:
        conn.execute(
            "UPDATE timed_rounds SET sentences_json = ? WHERE session_id = ? AND round = ?",
            (json.dumps(sentences, ensure_ascii=False), session_id, round),
        )


def set_round_transcript(session_id, round, words, long_pauses, sentences) -> None:
    """A round whose first transcription failed, transcribed again from its
    stored recording: new stats and fresh, ungraded sentences (strings, as
    add_round takes them)."""
    with connect() as conn:
        conn.execute(
            "UPDATE timed_rounds SET words = ?, long_pauses = ?, sentences_json = ?"
            " WHERE session_id = ? AND round = ?",
            (words, long_pauses, _fresh_sentences_json(sentences), session_id, round),
        )


def set_round_native(session_id, round, native, level) -> None:
    with connect() as conn:
        conn.execute(
            "UPDATE timed_rounds SET native = ?, level = ? WHERE session_id = ? AND round = ?",
            (native, level, session_id, round),
        )


def history(language, offset, limit) -> list[dict]:
    """Finished sessions, newest first. A script session reads fixed lines, so
    none of its turns is wrong or graded; `graded` lets a row that was never
    graded (an old session, or every grading call failed) skip 고친 곳 0.
    `rounds` is only meaningful for a timed session -- how many times it was
    told the whole way through -- and is 0 for every other mode; timed's own
    `wrong`/`graded` stay the general (non-script) computation above since
    only round 1's sentences ever become messages rows."""
    with connect() as conn:
        rows = conn.execute(
            "SELECT s.id, s.scenario_id, s.topic, s.mode, s.ended_at, s.shadowing,"
            "  (SELECT COUNT(*) FROM messages m WHERE m.session_id = s.id AND m.speaker = 'user') turns,"
            "  CASE WHEN s.mode = 'script' THEN 0 ELSE"
            "  (SELECT COUNT(*) FROM messages m WHERE m.session_id = s.id AND m.speaker = 'user' AND m.ok = 0)"
            "  END wrong,"
            "  CASE WHEN s.mode = 'script' THEN 0 ELSE"
            "  (SELECT COUNT(*) FROM messages m WHERE m.session_id = s.id AND m.speaker = 'user' AND m.ok IS NOT NULL)"
            "  END graded,"
            "  CASE WHEN s.mode = 'timed' THEN"
            "  (SELECT COUNT(*) FROM timed_rounds tr WHERE tr.session_id = s.id) ELSE 0"
            "  END rounds"
            " FROM sessions s WHERE s.language = ? AND s.report IS NOT NULL"
            " ORDER BY s.ended_at DESC, s.id DESC LIMIT ? OFFSET ?", (language, limit, offset)).fetchall()
    return [dict(r) for r in rows]
